### ISSUE TITLE
kyber: Notes/feedback from Call 4 Agenda [ 2022-noaa-afsc ]

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#13]
Hi @seankross ! 

Thanks so much making this agenda. Here are some notes/feedback in no great order that you can feel free to ignore!

##  1. Could kyber be verbose about the total time when we create an md?

Maybe it did for you, but that would be helpful so the person could adjust. I noticed that this was 2 minutes over - see screenshot. I adjusted this in my most recent commit. 

<img width="608" alt="image" src="https://user-images.githubusercontent.com/5891909/155323151-45ad1909-3298-4094-9856-abe17a714ce1.png">

## 2. Could you add carriage returns when making the "sandwich":

Could we try before every column in the CohortRegistry?

I was writing out each time but I think it might just be every column: 
- before each Header 2 
- before effic-tip
- before incl-tip
- before closing

## 3. Any way to make the hyperlinks underlined?
It would make the hyperlinks stand out a bit more than they currently do (example "full version" below): 
<img width="276" alt="image" src="https://user-images.githubusercontent.com/5891909/155325918-6bb9121a-21c8-4c58-9818-737d2a454b66.png">

## 4. Any way to make the "pm" only show up after the second time?

This would make it say `Roll call • 12:00 - 12:02pm PT` Instead of `Roll call • 12:00pm - 12:02pm PT`. 

This might be a pain and is fine if it's not worth doing

## 5. Still having trouble with `[ ]`'s and `@` symbols
These are not a huge deal and I know have been a pain to format but just to report: 

a) it did a strange double 2022-noaa-afsc, in 2 fonts, and centered: 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/5891909/155322228-174e458b-9769-450e-8c7d-b49f91c108db.png">

b) and did a double for twitter and github handles (I can also remove the `@` symbols)

<img width="462" alt="image" src="https://user-images.githubusercontent.com/5891909/155323404-9bfff2e4-efe6-4dfa-b18c-edbb3dc25e69.png">

## Julie's notes to self

- I knitted Sean's md in RStudio, and pasted it into a Google Doc: 03_CallAgenda [ 2022-noaa-afsc ]
- Changed font to Open Sans - full doc
- Made "_opening.Rmd" part 9 point font
- Made "call X" as Title font 18, bold ; update Title to match (this makes gdoc table of contents better)
- Made Header 2 font 14, bold; update heading 2 to match
- Toggled "add" then "remove space after paragraph" throughout to make spacing a little more cozy

**Comment by stefaniebutland** [comment]
I've confirmed that the GDoc formatting issue above remains, even if I open agenda.html from browser by File > open

**Comment by stefaniebutland** [comment]
Julie's item 5a) (strange double 2022-noaa-afsc, in 2 fonts, and centered) appears to be resolved as of May 8, 2023

**Comment by stefaniebutland** [comment]
Stef's wishlist for Agenda doc:
- date format as 10:00 - 11:30 am Pacific Time (first occurrence)
- date format as 10:00 - 11:30 am PT (all following occurrences)
- extra minute in total time in Agenda created May 8, 2023

**Comment by seankross** [comment]
@jules32 @stefaniebutland I'm going to try to consolidate the agenda issues here. If I am missing any or you have any other comments about this list please let me know. I have some questions for you that I put in bold.

- [ ] ([From #1 in this comment](https://github.com/Openscapes/kyber/issues/13#issue-1149918205)) I believe this is now "fixed" in the sense that the start and end times reflect the cumulative sum of whatever duration is specified in the corresponding rmd files for that call. Therefore if the number of minutes runs over the scheduled time, that's accurately reflected in the agenda timing. Therefore if things are running over you will need to adjust the duration in the rmd. **Please let me know if this make sense and if this is how you want this to work.**
- [ ] ([From #2 in this comment](https://github.com/Openscapes/kyber/issues/13#issue-1149918205)) **Do you still want this? Or could you just give me a little more clarification about what you want here?**
- [ ] ([From #3 in this comment](https://github.com/Openscapes/kyber/issues/13#issue-1149918205)) Underline hyperlinks
- [ ] ([From #4 in this comment](https://github.com/Openscapes/kyber/issues/13#issue-1149918205)) make the "pm" only show up after the second time
- [ ] ([From #5 in this comment](https://github.com/Openscapes/kyber/issues/13#issue-1149918205)) Still having trouble with [ ]'s and @ symbols. I think this is fixed? **Would you mind testing this out for me?**
- [ ] ([From this comment](https://github.com/Openscapes/kyber/issues/13#issuecomment-1540449647)) tweaks to time formatting. **last bullet point may be related to the first item on this list**

**Comment by jules32** [comment]
For #2 above, see Stef's notes :)
<img width="575" alt="image" src="https://github.com/Openscapes/kyber/assets/5891909/d5cb3a12-2cd7-4098-8fed-1b4e10f87965">

**Comment by stefaniebutland** [comment]
Sean your issue-condensing is really helpful. We checked off the items in your comment that are "done"/ ok as is.

**For # 2 above** we want this:
![Screenshot 2023-05-09 at 1 31 24 PM](https://github.com/Openscapes/kyber/assets/11927811/9c60117a-7381-4ada-84f7-73112768693b)

not this
![Screenshot 2023-05-09 at 1 31 48 PM](https://github.com/Openscapes/kyber/assets/11927811/253849d2-4296-4582-9f26-de88c19a82ff)

**Comment by seankross** [comment]
Perfect, thank you both so much!

**Comment by stefaniebutland** [comment]
Quoting Sean:
([From #4 in this comment](https://github.com/Openscapes/kyber/issues/13#issue-1149918205)) make the "pm" only show up after the second time


Yes please. Our desired date/time format if possible:
 - 10:00 - 11:30 am Pacific Time (first occurrence)
 - 10:00 - 11:30 am PT (all following occurrences)

**Comment by stefaniebutland** [comment]
ok finished testing and checking your checkboxes. Thank you Sean!

**Comment by seankross** [comment]
Hey @jules32 and @stefaniebutland, I think the latest version of kyber, on the main branch, fixes all of these issues. Would you mind reinstalling kyber, testing it out, and letting me know? Thanks.

**Comment by stefaniebutland** [comment]
- [x] `remotes::install_github("openscapes/kyber@main")`
- [ ] **make a new repo for 2023-superdogs-test cohort**

2 columns and links to slide decks missing from this table (screenshot cf [2023-nasa-champions repo](https://github.com/NASA-Openscapes/2023-nasa-champions) and text below table "**Cohort Call Digests** are posted as issues in this repo." is missing. Sorry if I missed some input.

![Screenshot 2023-05-11 at 2 23 22 PM](https://github.com/Openscapes/kyber/assets/11927811/34ef1e4f-4fa5-40fa-b7d8-e67d612b3a7c)

**To document:** 
- Ensure cohort metadata is in cohort registry sheet, including `google_drive_folder`, `cohort_name_long`
- Creating a repo creates local folder with README.Rmd
- When README.Rmd opens (in RStudio), add new cohort_name to yaml (as in snippet below).
- Knit/preview README.Rmd to convert to .md
- push or upload `README.md` and `horst-champions-trailhead.png`to repo OR should we be pushing whole local repo folder?

```
---
params:
  cohort_name: "2023-superdogs-test"
  cohort_registry: "https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/"
output: github_document
---
```



- [ ] make agenda
    - pls add one space between end time and 'am' text.  `10:00 - 10:02am` -> `10:00 - 10:02 am`
    - thank you for all the other great formatting edits!
- [ ] set up GitHub Clinic
    - [x] team
    - [ ] usernames
        - error: 
```
 > add_repo_to_team(repo_name, team_name, org = "openscapes")
Error in add_repo_to_team(repo_name, team_name, org = "openscapes") : 
  could not find function "add_repo_to_team"
```

You've already saved me so much time and mental effort with these updates Sean. Thank you!

**Comment by stefaniebutland** [comment]
How do we create a new repo in another GitHub org, like `nmfs-openscapes`? In the past I've created in Openscapes GitHub org, then changed owner. Is it possible to define the org at the start?

**Comment by seankross** [comment]
> readme table issues

It looks like the way that kyber makes these tables is outdated. Is there a doc or file that has the correspondence between the cohort_type, call number, and the corresponding link? Maybe this is in kyber already and I forgot about it? I don't think it's in the [agendas](https://github.com/Openscapes/kyber/tree/main/inst/agendas) but I could be wrong.

> `add_repo_to_team`

Try using `add_team_to_repo()`. Sorry this is my fault, I named it stupidly the first time around.

> How do we create a new repo in another GitHub org, like nmfs-openscapes?

Try: `init_repo("2023-superdogs-test", org = "nmfs-openscapes")`

Thank you for the "to document" notes, it is super helpful! Also Stef do you use RStudio when doing kyber stuff or do you have another setup?

**Comment by seankross** [comment]
Added space between time and am/pm in [40b26cf](https://github.com/Openscapes/kyber/commit/40b26cf12983962c1457766111e2c88f14d532b3).

**Comment by stefaniebutland** [comment]
> Try using `add_team_to_repo()`

it worked!

> How do we create a new repo in another GitHub org, like `nmfs-openscapes`?
> Try: `init_repo("2023-superdogs-test", org = "nmfs-openscapes")`

it worked!

> do you use RStudio when doing kyber stuff 

I use RStudio

> It looks like the way that kyber makes these tables is outdated.

I think it was fine via kyber when I made the https://github.com/NASA-Openscapes/2023-nasa-champions repo Feb 15, 2023 (commit [8f50561](https://github.com/NASA-Openscapes/2023-nasa-champions/commit/8f5056118f3cfd30b1609bd542e461efb04b0e32))

> Added space between time and am/pm in [40b26cf](https://github.com/Openscapes/kyber/commit/40b26cf12983962c1457766111e2c88f14d532b3).

I don't see this change. I reinstalled kyber May 15 and ran:
```
kyber::call_agenda(
  registry_url = "https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/edit#gid=942365997", 
  cohort_id = "2023-superdogs-test", 
  call_number = 3)
```

**Comment by seankross** [comment]
@stefaniebutland the code that creates the schedule table only creates two columns: https://github.com/Openscapes/kyber/blob/main/R/readme_setup.R#L16. Do you know where else that information could have come from?

**Comment by stefaniebutland** [comment]
@jules32 are you able to help here? Please see Sean's [comment above](https://github.com/Openscapes/kyber/issues/13#issuecomment-1544959777) on readme table issues
> It looks like the way that kyber makes these tables is outdated. Is there a doc or file that has the correspondence between the cohort_type, call number, and the corresponding link? Maybe this is in kyber already and I forgot about it? I don't think it's in the [agendas](https://github.com/Openscapes/kyber/tree/main/inst/agendas?rgh-link-date=2023-05-12T01%3A07%3A11Z) but I could be wrong.

I just realized I prob made the last one manually by copying another README

**Comment by jules32** [comment]
Hi @seankross and @stefaniebutland , ah yes the README table I believe has not been made programmatically in the past, I originally made it by hand for the READMEs. 

There isn't currently a "doc or file that has the correspondence between the cohort_type, call number, and the corresponding link" – but I've just started a new tab in the [CohortRegistry](https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/edit#gid=3897547). 

Stef, I was thinking it would be better to fill with series chapter links (vs slides links). Would you make the final call and  add? Thank you!

<img width="386" alt="image" src="https://github.com/Openscapes/kyber/assets/5891909/47d1892d-0d05-49df-b405-a72b035cc728">

**Comment by stefaniebutland** [comment]
This is a good idea Julie. 

- What section do I link to for Next steps?
- for Onboarding I linked to https://openscapes.github.io/series/core-lessons/better-science.html 
- I added a GitHub strategies row

![Screenshot 2023-05-19 at 10 13 42 PM](https://github.com/Openscapes/kyber/assets/11927811/0e556343-7839-4be3-bc50-073b33780133)

**Comment by jules32** [comment]
Awesome, thanks Stef! I think it's fine with no link right now for Next Steps

**Comment by stefaniebutland** [comment]
Consolidating the remaining items by opening new issues:

- [ ] Add to documentation #72
- [ ] Formatting Google doc, Any way to make hyperlinks underlined? #73
- [ ] Make README table programmatically #74

**Comment by stefaniebutland** [comment]
closing since remaining items are in separate new issues
