### ISSUE TITLE
Kyber Roadmap to 0.1.0

### ISSUE THREAD

**Issue by seankross** [Openscapes/kyber#20]
This documentation lives in the package repo (as a packagedown website?) one source of truth, and [approach-guide](https://openscapes.github.io/approach-guide/champions/pre-cohort-tech.html#github-repo) will link to that (Julie writes in the approach-guide)

Documentation:
- [x] Configuration
  - [x] setting up and troubleshooting googlesheets4
  - [x] github pat management
- [ ] How to create a github repo 
  - [ ] How to create a readme.md for a cohort 
  - [ ] And add code-of-conduct.md
- [ ] how to Create clinic
- [ ] how to Create team and add usernames
- [ ] How to create a call agenda
  - include: https://github.com/Openscapes/kyber/issues/9
  - and : https://github.com/Openscapes/kyber/issues/13
- [ ] Update README.md https://github.com/Openscapes/kyber/blob/dev/README.md 
- [ ] Write vignette: "Kyber without Openscapes"

Features:
- [x] Make sure that adding a code of conduct works
- [x] make a totally new create readme function based on https://github.com/Openscapes/kyber/issues/18
- [x] Make sure clinic creation handles names
  - https://github.com/Openscapes/kyber/issues/1
  - https://github.com/Openscapes/kyber/issues/3
- [x] https://github.com/Openscapes/kyber/issues/4
- [x] When you make an agenda make sure image is copied to wherever the readme is:
  - https://github.com/Openscapes/kyber/issues/14

Housekeeping:
- [x] get rid of `ky_` prefix

**Comment by seankross** [comment]
Notes from 2022-12-06 meeting:

- Warn of cohort id does not exist in the google sheet
- Fix annoying latex title header crap
- init_repo() was hanging indefinitely and crashed R eventually

**Comment by stefaniebutland** [comment]
@seankross Can we close this issue? I see Kyber is already at 0.1.0 and all tasks have been completed except Write vignette: "Kyber without Openscapes", which we aren't ready to do yet

**Comment by seankross** [comment]
@stefaniebutland sounds good to me
